Review
ButchCoolige/stellar-burgers pull request #1
Opened 2024-12-04 08:10 UTC by ButchCoolige

2024-12-04 12:01 UTC, aromanovnik requested changes
Добрый день, Butch!

Работа выполнена очень хорошо: написаны селекторы, хорошее понимание Redux, createAsyncThunk и использование lifecycle actions. Регистрация и работа с пользователем реализованы корректно, конструктор бургера работает правильно, оформление заказа тоже функционирует. Код выглядит чисто и структурированно.

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

Что нужно исправить:
* Модальные окна должны открываться в виде модального окна, а не как полноценная страница. Для этого в проекте следует использовать `{ background: Location }` вместо `{ backgroundLocation: Location }`.
* Для атрибута `key` в конструкторе нужно использовать для ингредиента уникальный `uuid` (Вам нужно его генерировать во время сброса в зону заказа). Это можно делать с помощью библиотеки uuid https://www.npmjs.com/package/uuid , или Вам должны были показать, как это сделать, иначе некорректно может работать DND. А в key будет уже просто `key={ item.uniqueId }`

Что можно улучшить:
* Если в **createAsyncThunk** нужно просто вызвать функцию запроса и получить возвращаемое знание, без какой либо его обработки, то не нужно создавать функцию обертку. Лучше просто передать саму функцию запроса в качестве аргумента, например `createAsyncThunk<TFeedsResponse>('burger/getFeed', getFeedsApi);`
* При заходе по прямой ссылке на страницу `/profile` авторизованным пользователем сначала происходит редирект на `/login`, а затем обратно на `/profile`. Вместо такого поведения, пока информация о пользователе не загружена, следует отображать прелоадер. Использовать флаг `isLoading` для этого не совсем корректно, так как он обычно отвечает только за текущий статус выполнения запроса. Более подходящий вариант — ввести отдельный флаг, например, `isAuthChecked: false`, который будет меняться на `true` только после завершения проверки авторизации пользователя. Это сделает логику проверки более ясной и изолированной.
* Закомментированный код лучше удалять, так как он засоряет проект, снижает его читаемость и может вводить в заблуждение. История изменений сохраняется в системе контроля версий, такой как Git, где всегда можно восстановить удаленный код, если он потребуется. 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-12-04 12:01 UTC, aromanovnik commented on src/services/slices/feedSlice.tsx
> +const getFeed = createAsyncThunk<TFeedsResponse>('burger/getFeed', async () => {
**Можно лучше**: Если в **createAsyncThunk** нужно просто вызвать функцию запроса и получить возвращаемое знание, без какой либо его обработки, то не нужно создавать функцию обертку. Лучше просто передать саму функцию запроса в качестве аргумента, например `createAsyncThunk<TFeedsResponse>('burger/getFeed', getFeedsApi);`

2024-12-04 12:01 UTC, aromanovnik commented on src/components/app/app.tsx
> +  const state = location.state as { backgroundLocation?: Location };
**Надо исправить**: Модальные окна должны открываться в виде модального окна, а не как полноценная страница. Для этого в проекте следует использовать `{ background: Location }` вместо `{ backgroundLocation: Location }`.

<img width="988" alt="Screenshot 2024-12-04 at 14 26 17" src="https://github.com/user-attachments/assets/2b5d2ceb-81fe-493c-bca5-7e72e6b266b1">

2024-12-04 12:01 UTC, aromanovnik commented on src/components/burger-constructor-element/burger-constructor-element.tsx
>  export const BurgerConstructorElement: FC<BurgerConstructorElementProps> = memo(
**Надо исправить**: Для атрибута `key` в конструкторе нужно использовать для ингредиента уникальный `uuid` (Вам нужно его генерировать во время сброса в зону заказа). Это можно делать с помощью библиотеки uuid https://www.npmjs.com/package/uuid , или Вам должны были показать, как это сделать, иначе некорректно может работать DND. А в key будет уже просто `key={ item.uniqueId }`

<img width="1456" alt="Screenshot 2024-12-04 at 14 30 52" src="https://github.com/user-attachments/assets/8330ec31-53f6-433e-a2a2-bcc9734e2a8d">

2024-12-04 12:01 UTC, aromanovnik commented on src/components/feed-info/feed-info.tsx
> +  if (loading) return <Preloader />;
**Можно лучше**: При заходе по прямой ссылке на страницу `/profile` авторизованным пользователем сначала происходит редирект на `/login`, а затем обратно на `/profile`. Вместо такого поведения, пока информация о пользователе не загружена, следует отображать прелоадер. Использовать флаг `isLoading` для этого не совсем корректно, так как он обычно отвечает только за текущий статус выполнения запроса. Более подходящий вариант — ввести отдельный флаг, например, `isAuthChecked: false`, который будет меняться на `true` только после завершения проверки авторизации пользователя. Это сделает логику проверки более ясной и изолированной.

2024-12-04 12:01 UTC, aromanovnik commented on src/components/app/app.tsx
> +/* const appRoutes = [
**Можно лучше**: Закомментированный код лучше удалять, так как он засоряет проект, снижает его читаемость и может вводить в заблуждение. История изменений сохраняется в системе контроля версий, такой как Git, где всегда можно восстановить удаленный код, если он потребуется.

2024-12-06 16:42 UTC, ButchCoolige commented on src/components/feed-info/feed-info.tsx
> +  if (loading) return <Preloader />;
Попробовал. Сходу не вышло. Очень много ошибок вылезло. Займусь плотнее позже. Сейчас время поджимает сильно...

2024-12-06 16:43 UTC, ButchCoolige commented on src/services/slices/feedSlice.tsx
> +const getFeed = createAsyncThunk<TFeedsResponse>('burger/getFeed', async () => {
Спасибо за замечание!

2024-12-06 19:16 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. Желаю успехов в дальнейшей учебе!

2024-12-15 06:34 UTC, merged